### ISSUE TITLE
Fetch demo has some problems executing

### ISSUE THREAD

**Issue by schmerl** [TheRobotCooperative/TheRobotCooperative#50]
The demo for fetch described on http://docs.fetchrobotics.com/gazebo.html#running-the-mobile-manipulation-demo has some problems in the built docker image. 

## Issue 1: The robot gets to the table and just rotates/oscillates

This (maybe) turns out to be a problem with the inflation radius in the planner. This can be fixed by changing it to 0.05 in `/ros_ws/src/fetch_ros/fetch_navigation/config/costmap_common.yaml`. Change it to:

```yaml
robot_base_frame: base_link

transform_tolerance: 0.5

robot_radius: 0.30
inflater:
  robot_radius: 0.30
  inflation_radius: 0.05

# Obstacles are defined in robot folders
```

## Issue 2: There is a python error when trying to grab the object on the table

After the robot raises its torso at the first table, it tries to pick up the object. But this python error occurs:

```
Traceback (most recent call last):
  File "/ros_ws/src/fetch_gazebo/fetch_gazebo_demo/scripts/demo.py", line 274, in <module>
    grasping_client.updateScene()
  File "/ros_ws/src/fetch_gazebo/fetch_gazebo_demo/scripts/demo.py", line 152, in updateScene
    wait = False)
TypeError: addSolidPrimitive() got an unexpected keyword argument 'wait'
```

This can be fixed by changing the calls in line 149-152 and 163-166 of `/ros_ws/src/fetch_gazebo/fetch_gazebo_demo/scripts/demo.py` to:

```python
            self.scene.addSolidPrimitive(obj.name,
                                         obj.primitives[0],
                                         obj.primitive_poses[0])
#                                         wait = False)
```

## Issue 3: The robot cannot go through the door to the second table

Not sure how to resolve this

It's possible that this is indicative of a larger error of some versioning mismatches on the grabbed sources.

**Comment by ChrisTimperley** [comment]
@afsafzal and @DebyKatz may also find this interesting and informative.

**Comment by afsafzal** [comment]
This seems to be the fix for the demo: https://github.com/fetchrobotics/fetch_gazebo/pull/101
I tried it a couple times and it works, but apparently it's not super stable.
